name: TERRAFORM_CHECK

on:
  push:
    branches:
      - master
    paths: ['infra/terraform/**']
    
  pull_request:
    branches:
      - master
    paths: ['infra/terraform/**']

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.9.6"

    - name: Terraform Init
      working-directory: infra/terraform
      run: |
          terraform init -input=false
    
    - name: Validate
      working-directory: infra/terraform
      run: |
        echo "Validating tf code"
        terraform validate